# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    container.autowiring.strict_mode: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Nines\BlogBundle\Menu\Builder:
        tags:
        - { name: knp_menu.menu_builder, method: postNavMenu, alias: posts}
        - { name: knp_menu.menu_builder, method: pageNavMenu, alias: pages}

    Nines\UserBundle\Menu\Builder:
        tags:
        - { name: knp_menu.menu_builder, method: userNavMenu, alias: user}

    AppBundle\Menu\Builder:
        public: true
        tags:
        - { name: knp_menu.menu_builder, method: mainMenu, alias: main}
